server:
  port: 10001
spring:
  application:
    name: sunxn-news-registry
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka
    register-with-eureka: false
    fetch-registry: false
