server:
  port: 8087
spring:
  application:
    name: webcrawler-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_news_system_web_crawler
    username: root
    password: x33334
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl