server:
  port: 10002
spring:
  application:
    name: sunxn-news-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka
zuul:
  prefix: /api  # 添加路由前置
  routes:
    webcrawler-service:
      path: /webcrawler/**
      serviceId: webcrawler-service
#      strip-prefix: false
    item-service: /item/**
    upload-service:
      path: /upload/**
      serviceId: upload-service
      strip-prefix: false
    search-service: /search/**
  add-host-header: true # 携带请求本身的head头信息
  sensitive-headers:    # 配置禁用使用的头信息，这里设置为null，否则set-cookie无效
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 # 熔断超时时长：5000ms
ribbon:
  ConnectTimeout: 1000  # ribbon连接超时时长
  ReadTimeout: 3500 # ribbon读取超时时长
  MaxAutoRetries: 0 # 当前服务重试次数
  MaxAutoRetriesNextServer: 0 #切换服务重试次数
sunxn:
  jwt:
    publicKeyPath: E:\prictice6_JavaEE\projects\web-crawler-news-system\rsakey\rsa.pub # 公钥地址
    cookieName: SUNXN_TOKEN
  filter:
    allowPaths: # 网关白名单,放行列表
      - /api/item/user/login